services:
  postgres:
    image: postgres:18.1-alpine3.22
    container_name: url_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - url_shortner_postgres_data:/var/lib/postgresql/data
  counter:
    image: redis:8.4-alpine
    container_name: counter_db
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --save 60 1
    volumes:
      - redis_data:/data
  cache:
    image: redis:8.4-alpine
    container_name: cache_db
    restart: unless-stopped
    ports:
      - "6378:6379"
    command: >
      redis-server
      --save ""
      --appendonly no
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru

volumes:
  url_shortner_postgres_data:
  redis_data:
